[package]
name = "day_19"
version = "0.1.0"
edition = "2021"

[lib]
name = "day_19"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
